const startingPoints = [
  {
    address: '1745 T Street Southeast',
    city: 'Washington',
    state: 'DC',
    zip: '20020',
  },
  {
    address: '6007 Applegate Lane',
    city: 'Louisville',
    state: 'KY',
    zip: '40219',
  },
  {
    address: '560 Penstock Drive',
    city: 'Grass Valley',
    state: 'CA',
    zip: '95945',
  },
  {
    address: '150 Carter Street',
    city: 'Manchester',
    state: 'CT',
    zip: '06040',
  },
  {
    address: '2721 Lindsay Avenue',
    city: 'Louisville',
    state: 'KY',
    zip: '40206',
  },
  {
    address: '18 Densmore Drive',
    city: 'Essex',
    state: 'VT',
    zip: '05452',
  },
  {
    address: '637 Britannia Drive',
    city: 'Vallejo',
    state: 'CA',
    zip: '94591',
  },
  {
    address: '5601 West Crocus Drive',
    city: 'Glendale',
    state: 'AZ',
    zip: '85306',
  },
  {
    address: '5403 Illinois Avenue',
    city: 'Nashville',
    state: 'TN',
    zip: '37209',
  },
  {
    address: '8821 West Myrtle Avenue',
    city: 'Glendale',
    state: 'AZ',
    zip: '85305',
  },
  {
    address: '2203 7th Street Road',
    city: 'Louisville',
    state: 'KY',
    zip: '40208',
  },
  {
    address: '6463 Vrain Street',
    city: 'Arvada',
    state: 'CO',
    zip: '80003',
  },
  {
    address: '87 Horseshoe Drive',
    city: 'West Windsor',
    state: 'VT',
    zip: '05037',
  },
  {
    address: '60 Desousa Drive',
    city: 'Manchester',
    state: 'CT',
    zip: '06040',
  },
  {
    address: '4 Old Colony Way',
    city: 'Yarmouth',
    state: 'MA',
    zip: '02664',
  },
  {
    address: '314 South 17th Street',
    city: 'Nashville',
    state: 'TN',
    zip: '37206',
  },
  {
    address: '1649 Timberridge Court',
    city: 'Fayetteville',
    state: 'AR',
    zip: '72704',
  },
  {
    address: '5461 West Shades Valley Drive',
    city: 'Montgomery',
    state: 'AL',
    zip: '36108',
  },
  {
    address: '629 Debbie Drive',
    city: 'Nashville',
    state: 'TN',
    zip: '37076',
  },
  {
    address: '22572 Toreador Drive',
    city: 'Salinas',
    state: 'CA',
    zip: '93908',
  },
  {
    address: '3034 Mica Street',
    city: 'Fayetteville',
    state: 'AR',
    zip: '72704',
  },
  {
    address: '3729 East Mission Boulevard',
    city: 'Fayetteville',
    state: 'AR',
    zip: '72703',
  },
  {
    address: '5114 Greentree Drive',
    city: 'Nashville',
    state: 'TN',
    zip: '37211',
  },
  {
    address: '3466 Southview Avenue',
    city: 'Montgomery',
    state: 'AL',
    zip: '36111',
  },
  {
    address: '1513 Cathy Street',
    city: 'Savannah',
    state: 'GA',
    zip: '31415',
  },
  {
    address: '600 West 19th Avenue',
    city: 'Anchorage',
    state: 'AK',
    zip: '99503',
  },
  {
    address: '1208 Elkader Court North',
    city: 'Nashville',
    state: 'TN',
    zip: '37013',
  },
  {
    address: '210 Green Road',
    city: 'Manchester',
    state: 'CT',
    zip: '06042',
  },
  {
    address: '49548 Road 200',
    city: "O'Neals",
    state: 'CA',
    zip: '93645',
  },
  {
    address: '81 Seaton Place Northwest',
    city: 'Washington',
    state: 'DC',
    zip: '20001',
  },
  {
    address: '1267 Martin Street',
    city: 'Nashville',
    state: 'TN',
    zip: '37203',
  },
  {
    address: '7431 Candace Way',
    city: 'Louisville',
    state: 'KY',
    zip: '40214',
  },
  {
    address: '1407 Walden Court',
    city: 'Crofton',
    state: 'MD',
    zip: '21114',
  },
  {
    address: '5906 Milton Avenue',
    city: 'Deale',
    state: 'MD',
    zip: '20751',
  },
  {
    address: '74 Springfield Street',
    city: 'Agawam',
    state: 'MA',
    zip: '01001',
  },
  {
    address: '2905 Stonebridge Court',
    city: 'Norman',
    state: 'OK',
    zip: '73071',
  },
  {
    address: '20930 Todd Valley Road',
    city: 'Foresthill',
    state: 'CA',
    zip: '95631',
  },
  {
    address: '5928 West Mauna Loa Lane',
    city: 'Glendale',
    state: 'AZ',
    zip: '85306',
  },
  {
    address: '802 Madison Street Northwest',
    city: 'Washington',
    state: 'DC',
    zip: '20011',
  },
  {
    address: '2811 Battery Place Northwest',
    city: 'Washington',
    state: 'DC',
    zip: '20016',
  },
  {
    address: '210 Lacross Lane',
    city: 'Westmore',
    state: 'VT',
    zip: '05860',
  },
  {
    address: '2010 Rising Hill Drive',
    city: 'Norman',
    state: 'OK',
    zip: '73071',
  },
  {
    address: '388 East Main Street',
    state: 'VT',
    zip: '05753',
  },
  {
    address: '450 Kinhawk Drive',
    city: 'Nashville',
    state: 'TN',
    zip: '37211',
  },
  {
    address: '131 Westerly Street',
    city: 'Manchester',
    state: 'CT',
    zip: '06042',
  },
  {
    address: '308 Woodleaf Court',
    city: 'Glen Burnie',
    state: 'MD',
    zip: '21061',
  },
  {
    address: '8502 Madrone Avenue',
    city: 'Louisville',
    state: 'KY',
    zip: '40258',
  },
  {
    address: '23 Sable Run Lane',
    city: 'Methuen',
    state: 'MA',
    zip: '01844',
  },
  {
    address: '716 Waller Road',
    city: 'Brentwood',
    state: 'TN',
    zip: '37027',
  },
  {
    address: '416 McIver Street',
    city: 'Nashville',
    state: 'TN',
    zip: '37211',
  },
  {
    address: '1508 Massachusetts Avenue Southeast',
    city: 'Washington',
    state: 'DC',
    zip: '20003',
  },
  {
    address: '5615 West Villa Maria Drive',
    city: 'Glendale',
    state: 'AZ',
    zip: '85308',
  },
  {
    address: '3162 Martin Luther King Junior Boulevard',
    city: 'Fayetteville',
    state: 'AR',
    zip: '72704',
  },
  {
    address: '5306 Ritchie Highway',
    city: 'Baltimore',
    state: 'MD',
    zip: '21225',
  },
  {
    address: '109 Summit Street',
    city: 'Burlington',
    state: 'VT',
    zip: '05401',
  },
  {
    address: '816 West 19th Avenue',
    city: 'Anchorage',
    state: 'AK',
    zip: '99503',
  },
  {
    address: '172 Alburg Springs Road',
    city: 'Alburgh',
    state: 'VT',
    zip: '05440',
  },
  {
    address: '159 Downey Drive',
    city: 'Manchester',
    state: 'CT',
    zip: '06040',
  },
  {
    address: '125 John Street',
    city: 'Santa Cruz',
    state: 'CA',
    zip: '95060',
  },
  {
    address: '1101 Lotus Avenue',
    city: 'Glen Burnie',
    state: 'MD',
    zip: '21061',
  },
  {
    address: '8376 Albacore Drive',
    city: 'Pasadena',
    state: 'MD',
    zip: '21122',
  },
  {
    address: '491 Arabian Way',
    city: 'Grand Junction',
    state: 'CO',
    zip: '81504',
  },
  {
    address: '12245 West 71st Place',
    city: 'Arvada',
    state: 'CO',
    zip: '80004',
  },
  {
    address: '80 North East Street',
    city: 'Holyoke',
    state: 'MA',
    zip: '01040',
  },
  {
    address: '4695 East Huntsville Road',
    city: 'Fayetteville',
    state: 'AR',
    zip: '72701',
  },
  {
    address: '310 Timrod Road',
    city: 'Manchester',
    state: 'CT',
    zip: '06040',
  },
  {
    address: '1364 Capri Drive',
    city: 'Panama City',
    state: 'FL',
    zip: '32405',
  },
  {
    address: '132 Laurel Green Court',
    city: 'Savannah',
    state: 'GA',
    zip: '31419',
  },
  {
    address: '6657 West Rose Garden Lane',
    city: 'Glendale',
    state: 'AZ',
    zip: '85308',
  },
  {
    address: '519 West 75th Avenue',
    city: 'Anchorage',
    state: 'AK',
    zip: '99518',
  },
  {
    address: '31353 Santa Elena Way',
    city: 'Union City',
    state: 'CA',
    zip: '94587',
  },
  {
    address: '8398 West Denton Lane',
    city: 'Glendale',
    state: 'AZ',
    zip: '85305',
  },
  {
    address: '700 Winston Place',
    city: 'Anchorage',
    state: 'AK',
    zip: '99504',
  },
  {
    address: '232 Maine Avenue',
    city: 'Panama City',
    state: 'FL',
    zip: '32401',
  },
  {
    address: '1 Kempf Drive',
    city: 'Easton',
    state: 'MA',
    zip: '02375',
  },
  {
    address: '5811 Crossings Boulevard',
    city: 'Nashville',
    state: 'TN',
    zip: '37013',
  },
  {
    address: '5108 Franklin Street',
    city: 'Savannah',
    state: 'GA',
    zip: '31405',
  },
  {
    address: '913 Fallview Trail',
    city: 'Nashville',
    state: 'TN',
    zip: '37211',
  },
  {
    address: "270 Chrissy's Court",
    city: 'Bristol',
    state: 'VT',
    zip: '05443',
  },
  {
    address: '130 Old Route 103',
    city: 'Chester',
    state: 'VT',
    zip: '05143',
  },
  {
    address: '10826 Pointe Royal Drive',
    city: 'Bakersfield',
    state: 'CA',
    zip: '93311',
  },
  {
    address: '74 Ranch Drive',
    city: 'Montgomery',
    state: 'AL',
    zip: '36109',
  },
  {
    address: '6601 West Ocotillo Road',
    city: 'Glendale',
    state: 'AZ',
    zip: '85301',
  },
  {
    address: '19416 Barclay Road',
    city: 'Castro Valley',
    state: 'CA',
    zip: '94546',
  },
  {
    address: '1347 Blackwalnut Court',
    city: 'Annapolis',
    state: 'MD',
    zip: '21403',
  },
  {
    address: '1770 Colony Way',
    city: 'Fayetteville',
    state: 'AR',
    zip: '72704',
  },
  {
    address: '165 Saint John Street',
    city: 'Manchester',
    state: 'CT',
    zip: '06040',
  },
  {
    address: '2409 Research Boulevard',
    city: 'Fort Collins',
    state: 'CO',
    zip: '80526',
  },
  {
    address: '1903 Bashford Manor Lane',
    city: 'Louisville',
    state: 'KY',
    zip: '40218',
  },
  {
    address: '8315 Surf Drive',
    city: 'Panama City Beach',
    state: 'FL',
    zip: '32408',
  },
  {
    address: '3301 Old Muldoon Road',
    city: 'Anchorage',
    state: 'AK',
    zip: '99504',
  },
  {
    address: '8800 Cordell Circle',
    city: 'Anchorage',
    state: 'AK',
    zip: '99502',
  },
  {
    address: '117 East Cook Avenue',
    city: 'Anchorage',
    state: 'AK',
    zip: '99501',
  },
  {
    address: '6231 North 67th Avenue',
    city: 'Glendale',
    state: 'AZ',
    zip: '85301',
  },
  {
    address: '8505 Waters Avenue',
    city: 'Savannah',
    state: 'GA',
    zip: '31406',
  },
  {
    address: '7 Underwood Place Northwest',
    city: 'Washington',
    state: 'DC',
    zip: '20012',
  },
  {
    address: '21950 Arnold Center Road',
    city: 'Carson',
    state: 'CA',
    zip: '90810',
  },
  {
    address: '1427 South Carolina Avenue Southeast',
    city: 'Washington',
    state: 'DC',
    zip: '20003',
  },
  {
    address: '1420 Turtleback Trail',
    city: 'Panama City',
    state: 'FL',
    zip: '32413',
  },
];

module.exports = startingPoints;
