const trips = [
  { name: 'Brolga crane' },
  { name: 'Red-tailed wambenger' },
  { name: 'Tern, royal' },
  { name: 'Red deer' },
  { name: "Gazelle, thomson's" },
  { name: 'Gecko, tokay' },
  { name: 'European wild cat' },
  { name: 'Gulls (unidentified)' },
  { name: 'Mule deer' },
  { name: 'Waxbill, blue' },
  { name: 'Banded mongoose' },
  { name: 'Pygmy possum' },
  { name: 'Canadian river otter' },
  { name: 'Gerbil (unidentified)' },
  { name: 'Fox, silver-backed' },
  { name: 'Dragon, komodo' },
  { name: 'Vulture, turkey' },
  { name: 'Lilac-breasted roller' },
  { name: 'Barbet, crested' },
  { name: 'Sloth, two-toed' },
  { name: 'Starling, red-shouldered glossy' },
  { name: 'Black rhinoceros' },
  { name: 'Vulture, white-headed' },
  { name: 'Blue crane' },
  { name: "Gonolek, burchell's" },
  { name: 'Goose, cape barren' },
  { name: 'Shark, blue' },
  { name: 'Egret, great' },
  { name: 'Turtle, snake-necked' },
  { name: 'Whale, baleen' },
  { name: 'Common shelduck' },
  { name: 'Sacred ibis' },
  { name: 'Oryx, fringe-eared' },
  { name: 'Red howler monkey' },
  { name: 'Raven, cape' },
  { name: 'Skimmer, four-spotted' },
  { name: 'Snake, tiger' },
  { name: 'Fox, pampa gray' },
  { name: 'Scarlet macaw' },
  { name: "Gonolek, burchell's" },
  { name: 'Loris, slender' },
  { name: 'Asian water buffalo' },
  { name: 'Canadian river otter' },
  { name: 'Seal, northern elephant' },
  { name: 'Black-fronted bulbul' },
  { name: 'Cape fox' },
  { name: 'Spurfowl, yellow-necked' },
  { name: 'Stork, saddle-billed' },
  { name: 'Deer, barasingha' },
  { name: 'Cockatoo, roseate' },
  { name: 'Stork, painted' },
  { name: 'Bison, american' },
  { name: 'Mynah, common' },
  { name: 'Lizard, collared' },
  { name: 'Glossy ibis' },
  { name: 'Stilt, black-winged' },
  { name: 'Black-tailed prairie dog' },
  { name: "Barbet, levaillant's" },
  { name: 'Boa, mexican' },
  { name: 'Buffalo, american' },
  { name: 'Glider, sugar' },
  { name: 'Gull, kelp' },
  { name: 'Dragon, western bearded' },
  { name: 'Barbet, crested' },
  { name: 'Glider, squirrel' },
  { name: 'Waterbuck, common' },
  { name: 'Crocodile, nile' },
  { name: 'Bateleur eagle' },
  { name: 'Arctic tern' },
  { name: 'Praying mantis (unidentified)' },
  { name: 'Thrasher, curve-billed' },
  { name: 'Grey lourie' },
  { name: 'Common seal' },
  { name: 'Ibis, glossy' },
  { name: 'Neotropic cormorant' },
  { name: 'Bird, black-throated butcher' },
  { name: 'Pied cormorant' },
  { name: 'Fox, asian red' },
  { name: 'Bulbul, african red-eyed' },
  { name: 'Pigeon, wood' },
  { name: 'Black-capped chickadee' },
  { name: 'Hawk, galapagos' },
  { name: 'Zebra, common' },
  { name: 'Downy woodpecker' },
  { name: 'Trumpeter swan' },
  { name: 'Little brown dove' },
  { name: 'Crab (unidentified)' },
  { name: 'Madagascar hawk owl' },
  { name: 'Tern, arctic' },
  { name: 'Whale, baleen' },
  { name: 'Lily trotter' },
  { name: 'Red-shouldered glossy starling' },
  { name: 'White-throated robin' },
  { name: 'Grey mouse lemur' },
  { name: 'Lesser masked weaver' },
  { name: 'Cougar' },
  { name: 'Slender-billed cockatoo' },
  { name: 'Jackal, golden' },
  { name: 'Eurasian hoopoe' },
  { name: 'Ox, musk' },
];

module.exports = trips;
